/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { 
  Sparkles, 
  Brain, 
  Clock, 
  TrendingUp, 
  AlertCircle, 
  Zap, 
  Check, 
  Compass, 
  RotateCw, 
  Award,
  BookOpen
} from 'lucide-react';
import { Subject, Chapter, MockTest, DailyTask } from '../types';

interface AiPlannerServiceProps {
  subjects: Subject[];
  chapters: Chapter[];
  mocks: MockTest[];
  tasks: DailyTask[];
  onAddTask: (task: Omit<DailyTask, 'id'>) => void;
  onApplyGeneratedSchedule?: (newTasks: Omit<DailyTask, 'id'>[]) => void;
  onAddToast: (msg: string, type: 'success' | 'info' | 'warning' | 'error') => void;
}

interface GeneratedSlot {
  timeSlot: string;
  title: string;
  duration: number;
  subject: string;
  chapterSuggestion: string;
  type: 'REVISION' | 'NEW_TOPIC' | 'PRACTICE' | 'BREAK';
  guidance: string;
}

interface GeneratedPlan {
  rationale: string;
  dailyBreakdown: GeneratedSlot[];
  weeklyFocusAreas: string[];
  mockTestStrategy: string;
}

export default function AiPlannerService({
  subjects,
  chapters,
  mocks,
  tasks,
  onAddTask,
  onApplyGeneratedSchedule,
  onAddToast
}: AiPlannerServiceProps) {
  const [hoursPerDay, setHoursPerDay] = useState<number>(6);
  const [focusStyle, setFocusStyle] = useState<'balanced' | 'aggressive' | 'test-centric'>('balanced');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [loadStep, setLoadStep] = useState<number>(0);
  const [error, setError] = useState<string | null>(null);
  const [plan, setPlan] = useState<GeneratedPlan | null>(null);
  const [activeTab, setActiveTab] = useState<'plan' | 'strategy'>('plan');

  const incompleteChapters = chapters.filter(c => c.status !== 'COMPLETED');
  const recentMocks = [...mocks].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  const lastMock = recentMocks[0];

  const steps = [
    "🔍 Scanning your incomplete syllabus chapters...",
    "📊 Indexing weak topics & historical mock scores...",
    "📐 Engineering custom timezone study blocks...",
    "🔬 Aligning with general WBCS standards...",
    "👑 Polishing expert coach strategy and rationale..."
  ];

  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (isLoading) {
      setLoadStep(0);
      interval = setInterval(() => {
        setLoadStep(prev => {
          if (prev < steps.length - 1) return prev + 1;
          return prev;
        });
      }, 2500);
    }
    return () => clearInterval(interval);
  }, [isLoading]);

  // Parse time slots like "08:00 AM - 10:00 AM" or "10:30-12:00" into { start: "HH:MM", end: "HH:MM" }
  const parseTimeSlot = (slotStr: string): { start: string; end: string } => {
    let start = "08:00";
    let end = "10:00";
    try {
      const parts = slotStr.split("-").map(p => p.trim());
      if (parts.length >= 2) {
        const formatTime = (t: string) => {
          const isPM = t.toUpperCase().includes("PM");
          const isAM = t.toUpperCase().includes("AM");
          let cleaned = t.replace(/(AM|PM)/i, "").trim();
          let [hStr, mStr] = cleaned.split(":");
          let h = parseInt(hStr, 10);
          let m = mStr ? parseInt(mStr, 10) : 0;
          
          if (isPM && h < 12) h += 12;
          if (isAM && h === 12) h = 0;
          
          return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}`;
        };
        start = formatTime(parts[0]);
        end = formatTime(parts[1]);
      }
    } catch (err) {
      console.error("Time parsing issue:", err);
    }
    return { start, end };
  };

  const generateAILink = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/generate-schedule', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          subjects,
          chapters,
          mocks,
          userPreferences: {
            hoursPerDay,
            focusStyle
          }
        })
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || "Generation endpoint failed.");
      }

      setPlan(data);
      onAddToast("Daily study plan generated by Gemini!", "success");
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to reach AI Server.");
      onAddToast("Error generating study plan", "error");
    } finally {
      setIsLoading(false);
    }
  };

  const handleApplyToPlanner = () => {
    if (!plan || !onApplyGeneratedSchedule) return;

    const newTasks: Omit<DailyTask, 'id'>[] = plan.dailyBreakdown
      .filter(item => item.type !== 'BREAK') // skip breaks to keep planner focused, or keep them to represent the full day. Let's include them as low priority
      .map(item => {
        const { start, end } = parseTimeSlot(item.timeSlot);
        
        // Find corresponding subject ID
        const matchedSub = subjects.find(s => 
          s.title.toLowerCase().includes(item.subject.toLowerCase()) ||
          item.subject.toLowerCase().includes(s.title.toLowerCase())
        );

        let mappedPriority: 'HIGH' | 'MEDIUM' | 'LOW' = 'MEDIUM';
        if (item.type === 'NEW_TOPIC') mappedPriority = 'HIGH';
        if (item.type === 'BREAK') mappedPriority = 'LOW';

        return {
          title: `${item.title} (${item.chapterSuggestion})`,
          startTime: start,
          endTime: end,
          priority: mappedPriority,
          status: 'PENDING',
          subjectId: matchedSub?.id || undefined,
          recurring: false
        };
      });

    onApplyGeneratedSchedule(newTasks);
  };

  return (
    <div id="ai-study-scheduler" className="rounded-3xl border border-blue-100 bg-linear-to-b from-blue-50/10 to-transparent p-6 shadow-xs space-y-6">
      {/* Header Visual Row */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between border-b border-gray-100 pb-4">
        <div className="flex items-start gap-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-600 text-white shadow-md animate-pulse">
            <Sparkles className="h-6 w-6" />
          </div>
          <div>
            <h3 className="text-base font-black text-gray-900 flex items-center gap-1.5">
              <span>WBCS AI Study Scheduler</span>
              <span className="text-[10px] bg-red-100 text-red-700 px-2 py-0.5 rounded-full font-bold uppercase tracking-wider">Gemini Powered</span>
            </h3>
            <p className="text-xs text-gray-500">Formulates a tailored syllabus schedule based on your unstudied chapters and mock exam mistakes.</p>
          </div>
        </div>

        <div className="flex items-center gap-1.5 bg-gray-100 p-1 rounded-full text-xs font-bold text-gray-650">
          <span className="px-3 text-[11px]">Backlogs: <b>{incompleteChapters.length}</b> chapters</span>
          <span className="px-3 text-[11px] border-l border-gray-200">Recent Mock: <b>{lastMock ? `${lastMock.score}/${lastMock.totalMarks}` : "N/A"}</b></span>
        </div>
      </div>

      {/* Control Inputs Box */}
      {!plan && !isLoading && (
        <div className="bg-white rounded-2xl border border-gray-100 p-5 space-y-5">
          <div className="grid gap-6 md:grid-cols-2">
            {/* Hours Available input */}
            <div className="space-y-2">
              <label className="text-xs font-black text-gray-800 uppercase tracking-wide flex items-center gap-1">
                <Clock className="h-4 w-4 text-blue-600" />
                <span>Available daily hours: <span className="text-blue-600 text-bold font-black">{hoursPerDay} Hrs</span></span>
              </label>
              <div className="flex flex-wrap gap-2">
                {[4, 6, 8, 10, 12].map(hrs => (
                  <button
                    key={hrs}
                    type="button"
                    onClick={() => setHoursPerDay(hrs)}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                      hoursPerDay === hrs 
                        ? 'bg-blue-600 text-white shadow-sm'
                        : 'bg-slate-50 text-slate-600 hover:bg-slate-100 border border-slate-200'
                    }`}
                  >
                    {hrs} Hours
                  </button>
                ))}
              </div>
              <p className="text-[10px] text-gray-400">Specify typical study session bandwidth per 24 hours.</p>
            </div>

            {/* Strategic Focus Mode */}
            <div className="space-y-2">
              <label className="text-xs font-black text-gray-800 uppercase tracking-wide flex items-center gap-1">
                <Compass className="h-4 w-4 text-blue-600" />
                <span>Coach Priority Mode</span>
              </label>
              <div className="grid grid-cols-3 gap-2">
                <button
                  type="button"
                  onClick={() => setFocusStyle('balanced')}
                  className={`p-2.5 rounded-xl text-center border transition-all ${
                    focusStyle === 'balanced' 
                      ? 'border-blue-500 bg-blue-50/40 text-blue-800 font-extrabold'
                      : 'border-gray-200 text-gray-600 hover:bg-slate-50'
                  }`}
                >
                  <span className="block text-xs">Balanced</span>
                  <span className="text-[9px] text-gray-400 block mt-0.5">Mix study & review</span>
                </button>

                <button
                  type="button"
                  onClick={() => setFocusStyle('aggressive')}
                  className={`p-2.5 rounded-xl text-center border transition-all ${
                    focusStyle === 'aggressive' 
                      ? 'border-red-500 bg-red-50/30 text-red-800 font-extrabold'
                      : 'border-gray-200 text-gray-600 hover:bg-slate-50'
                  }`}
                >
                  <span className="block text-xs">Aggressive</span>
                  <span className="text-[9px] text-gray-400 block mt-0.5">Clear backlogs fast</span>
                </button>

                <button
                  type="button"
                  onClick={() => setFocusStyle('test-centric')}
                  className={`p-2.5 rounded-xl text-center border transition-all ${
                    focusStyle === 'test-centric' 
                      ? 'border-emerald-500 bg-emerald-50/30 text-emerald-800 font-extrabold'
                      : 'border-gray-200 text-gray-600 hover:bg-slate-50'
                  }`}
                >
                  <span className="block text-xs">Test-Centric</span>
                  <span className="text-[9px] text-gray-400 block mt-0.5">Solve weak mocks</span>
                </button>
              </div>
            </div>
          </div>

          <div className="flex justify-center pt-2">
            <button
              onClick={generateAILink}
              className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-extrabold text-xs px-8 py-3.5 rounded-full shadow-lg hover:shadow-xl transition-all active:scale-95"
            >
              <Zap className="h-4 w-4 fill-white" />
              <span>Generate AI Study plan</span>
            </button>
          </div>
        </div>
      )}

      {/* Loading Block State */}
      {isLoading && (
        <div className="bg-white rounded-2xl border border-gray-100 p-8 text-center space-y-4">
          <div className="inline-block relative">
            <div className="h-14 w-14 rounded-full border-4 border-blue-200 border-t-blue-600 animate-spin" />
            <Sparkles className="h-5 w-5 text-blue-500 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 animate-scale-up" />
          </div>
          <div className="space-y-1">
            <h4 className="text-xs font-black text-gray-900 uppercase tracking-widest">Gemini is Thinking...</h4>
            <p className="text-xs text-blue-700 font-bold transition-all duration-300">{steps[loadStep]}</p>
          </div>
          <p className="text-[10px] text-gray-400 max-w-xs mx-auto">Evaluating West Bengal Civil Service exam weightings and scoring history to distribute study sessions perfectly.</p>
        </div>
      )}

      {/* Error Fallback */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-2xl p-4 flex items-start gap-3">
          <AlertCircle className="h-5 w-5 text-red-650 shrink-0" />
          <div className="space-y-1">
            <h4 className="text-xs font-extrabold text-red-950">Scheduler System Error</h4>
            <p className="text-xs text-red-700">{error}</p>
            <button
              onClick={() => { setError(null); generateAILink(); }}
              className="text-[10px] text-blue-700 font-bold underline hover:text-blue-900 mt-1 block"
            >
              Attempt recovery retry
            </button>
          </div>
        </div>
      )}

      {/* Output Rationale Card */}
      {plan && !isLoading && !error && (
        <div className="space-y-6">
          {/* Coach insights intro panel */}
          <div className="rounded-2xl border border-blue-50 bg-blue-50/20 p-5 space-y-3">
            <h4 className="text-xs font-black text-blue-950 uppercase tracking-wider flex items-center gap-1.5">
              <Brain className="h-4.5 w-4.5 text-blue-600" />
              <span>Coach Rationale & Advice</span>
            </h4>
            <div className="text-xs leading-relaxed text-slate-700 italic border-l-2 border-blue-400 pl-4 py-0.5">
              "{plan.rationale}"
            </div>
          </div>

          {/* Subtabs switches */}
          <div className="flex border-b border-gray-100">
            <button
              onClick={() => setActiveTab('plan')}
              className={`pb-3 text-xs font-black uppercase tracking-wider transition-colors mr-6 relative ${
                activeTab === 'plan' ? 'text-blue-700 border-b-2 border-blue-600' : 'text-gray-400 hover:text-gray-900'
              }`}
            >
              <span>Daily Study blocks Timeline</span>
            </button>
            <button
              onClick={() => setActiveTab('strategy')}
              className={`pb-3 text-xs font-black uppercase tracking-wider transition-colors relative ${
                activeTab === 'strategy' ? 'text-blue-700 border-b-2 border-blue-600' : 'text-gray-400 hover:text-gray-900'
              }`}
            >
              <span>Weekly Focus & Test strategy</span>
            </button>
          </div>

          {/* View Tab Details: PLAN */}
          {activeTab === 'plan' && (
            <div className="space-y-4">
              <div className="flex justify-between items-center bg-gray-50 rounded-2xl p-4">
                <div>
                  <h4 className="text-xs font-black text-gray-800">Gemini Optimized Hourly Sequence</h4>
                  <p className="text-[10px] text-gray-500">Includes core syllabus topics to clear remaining chapters backlog.</p>
                </div>
                {onApplyGeneratedSchedule && (
                  <button
                    onClick={handleApplyToPlanner}
                    className="flex items-center gap-1 text-xs bg-emerald-600 hover:bg-emerald-700 text-white px-4 py-2 rounded-xl font-bold transition-all shadow-sm"
                  >
                    <Check className="h-4 w-4" />
                    <span>Sync to Todays Active Planner</span>
                  </button>
                )}
              </div>

              <div className="grid gap-3 sm:grid-cols-2">
                {plan.dailyBreakdown.map((slot, idx) => {
                  const isBreak = slot.type === 'BREAK';
                  const isNewTopic = slot.type === 'NEW_TOPIC';
                  const isRevision = slot.type === 'REVISION';
                  return (
                    <div 
                      key={idx} 
                      className={`rounded-2xl border p-4 transition-all ${
                        isBreak 
                          ? 'border-gray-100 bg-gray-50 opacity-75' 
                          : isNewTopic
                            ? 'border-blue-150 bg-blue-50/10 hover:border-blue-300'
                            : isRevision
                              ? 'border-amber-150 bg-amber-50/10 hover:border-amber-300'
                              : 'border-emerald-150 bg-emerald-50/10 hover:border-emerald-300'
                      }`}
                    >
                      <div className="flex items-center justify-between">
                        <span className="text-[10px] font-bold text-slate-500 flex items-center gap-1">
                          <Clock className="h-3 w-3" /> {slot.timeSlot}
                        </span>
                        
                        <span className={`text-[8px] font-black uppercase tracking-wider px-2 py-0.5 rounded-full ${
                          isNewTopic ? 'bg-blue-100 text-blue-800' :
                          isRevision ? 'bg-amber-100 text-amber-800' :
                          isBreak ? 'bg-gray-200 text-gray-700' : 'bg-emerald-100 text-emerald-800'
                        }`}>
                          {slot.type}
                        </span>
                      </div>

                      <div className="mt-2 space-y-1">
                        <span className="text-[9px] font-bold text-gray-400 block uppercase">{slot.subject}</span>
                        <h5 className="text-xs font-black text-gray-900">{slot.title}</h5>
                        {!isBreak && (
                          <p className="text-[10px] text-slate-600 font-medium">
                            Target Backlog Chapter: <span className="underline font-bold text-blue-700">{slot.chapterSuggestion}</span>
                          </p>
                        )}
                        <p className="text-[10px] text-slate-500 leading-snug mt-1 pt-1.5 border-t border-dashed border-gray-100">
                          💡 <b>Tip:</b> {slot.guidance}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* View Tab Details: STRATEGY */}
          {activeTab === 'strategy' && (
            <div className="grid gap-5 md:grid-cols-2">
              {/* Weekly focus cards */}
              <div className="rounded-2xl border border-gray-100 bg-white p-5 space-y-4 shadow-3xs">
                <h4 className="text-xs font-black text-gray-800 uppercase tracking-wider flex items-center gap-1">
                  <BookOpen className="h-4.5 w-4.5 text-blue-600" />
                  <span>3 Strategic Weekly Targets</span>
                </h4>
                
                <div className="space-y-3.5">
                  {plan.weeklyFocusAreas.map((area, index) => (
                    <div key={index} className="flex items-start gap-2.5">
                      <span className="flex h-5 w-5 items-center justify-center rounded-full bg-blue-50 text-blue-700 text-xs font-black">
                        {index + 1}
                      </span>
                      <p className="text-xs text-slate-600">{area}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Mock Test Advice */}
              <div className="rounded-2xl border border-gray-100 bg-white p-5 space-y-4 shadow-3xs">
                <h4 className="text-xs font-black text-gray-800 uppercase tracking-wider flex items-center gap-1">
                  <Award className="h-4.5 w-4.5 text-blue-600" />
                  <span>Custom Mock test advice</span>
                </h4>
                
                <div className="text-xs leading-relaxed text-slate-600">
                  {plan.mockTestStrategy}
                </div>

                <div className="p-3.5 rounded-xl bg-orange-50/40 border border-orange-100 text-[10px] text-orange-850">
                  ⚠️ <b>Did you know?</b> An average General Category cutoff for WBCS Prelims sits around 125-132. Overcoming mock deficits on West Bengal districts & geography topics is crucial to secure high-weightage margins.
                </div>
              </div>
            </div>
          )}

          {/* Recalculate Option */}
          <div className="flex justify-end gap-2 border-t border-gray-100 pt-4">
            <button
              onClick={() => {
                setPlan(null);
              }}
              className="flex items-center gap-1.5 text-xs text-slate-500 hover:text-slate-800 font-bold px-4 py-2 border border-slate-200 rounded-xl bg-slate-50/50"
            >
              <RotateCw className="h-3.5 w-3.5" />
              <span>Modify settings & Recalculate</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
